# Re-export the canonical schemas from the u2 core library.
# The temporary local definitions that lived here have been replaced.
from u2.data_models import (
    BaseExogenousSeries,
    BaseSeries,
    Forecast,
    ForecastedTimeValue,
    ForecastExogenousSeries,
    ForecastInput,
    ForecastSeries,
    ForecastTargetSeries,
    ForecastTrainingInput,
    ForecastType,
    Location,
    ModelConfig,
    QuantileKey,
    QuantileLevel,
    TimeParameters,
    TimeValue,
    TrainingExogenousSeries,
    TrainingSplit,
    TrainingTargetSeries,
)

__all__ = [
    "BaseExogenousSeries",
    "BaseSeries",
    "Forecast",
    "ForecastedTimeValue",
    "ForecastExogenousSeries",
    "ForecastInput",
    "ForecastSeries",
    "ForecastTargetSeries",
    "ForecastTrainingInput",
    "ForecastType",
    "Location",
    "ModelConfig",
    "QuantileKey",
    "QuantileLevel",
    "TimeParameters",
    "TimeValue",
    "TrainingExogenousSeries",
    "TrainingSplit",
    "TrainingTargetSeries",
]
